# Generated by Django 5.2.8 on 2025-11-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("Admin", "Admin"), ("Doer", "Doer")],
                default="Doer",
                max_length=10,
            ),
        ),
    ]
