# Generated by Django 5.2.8 on 2025-11-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("Staff", "Staff"), ("Doer", "Doer")],
                default="Doer",
                max_length=10,
            ),
        ),
    ]
