# Generated by Django 5.2.8 on 2025-11-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MDO", "MDO"),
                    ("Accounts", "Accounts"),
                    ("CRM", "CRM"),
                    ("Sales", "Sales"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="mobile",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
